# Generated by Django 5.1.1 on 2024-11-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('domicilio', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
