# Generated by Django 5.1.2 on 2024-11-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(unique=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField()),
                ('fecha_nacimiento', models.DateField()),
                ('cargo', models.CharField(choices=[('vendedor', 'Vendedor'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador'), ('gerente', 'Gerente'), ('reponedor', 'Reponedor')], default='vendedor', max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
        ),
    ]
