# Generated by Django 5.1.2 on 2024-10-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.PositiveIntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('fechaIngreso', models.DateTimeField()),
                ('estadoLaboral', models.BooleanField()),
                ('cargo', models.CharField(choices=[('vendedor', 'Vendedor'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador'), ('gerente', 'Gerente'), ('reponedor', 'Reponedor')], default='vendedor', max_length=50)),
            ],
        ),
    ]
