# Generated by Django 5.1.2 on 2024-10-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estadoLaboral',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaIngreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
