# Generated by Django 5.1.2 on 2024-11-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0002_alter_empleado_estadolaboral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='estadoLaboral',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fechaIngreso',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
