# Generated by Django 5.1.2 on 2024-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0003_rename_estadolaboral_empleado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(),
        ),
    ]
