# Generated by Django 5.1.2 on 2024-11-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_empleados', '0001_initial'),
        ('gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('domicilio', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField(auto_now_add=True)),
                ('nroComprobante', models.IntegerField(unique=True)),
                ('tipoCliente', models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='Minorista', max_length=50)),
                ('formaPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='Efectivo', max_length=20)),
                ('montoTotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precioItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_ventas.venta')),
            ],
        ),
    ]
