# Generated by Django 5.1.2 on 2024-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0002_item_precioitem_item_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemayorista',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
