# Generated by Django 5.1.2 on 2024-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0003_clientemayorista_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemayorista',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
