# Generated by Django 5.1.2 on 2024-11-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0004_alter_empleado_cuit_alter_empleado_estado_and_more'),
        ('gestion_productos', '0002_alter_producto_cantidad_disponible_and_more'),
        ('gestion_ventas', '0004_alter_clientemayorista_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_productos.producto'),
        ),
    ]
