# Generated by Django 5.1.2 on 2024-11-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0005_venta_empleado_alter_item_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cantidadProducto',
            new_name='cantidad',
        ),
    ]
