# Generated by Django 5.1.2 on 2024-11-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(choices=[('kilogramos', 'Kilogramos'), ('litros', 'Litros'), ('unidad', 'Unidad'), ('gramos', 'Gramos')], default='Kilogramos', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoNum', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('idProveedor', models.IntegerField()),
                ('numComprobante', models.IntegerField()),
                ('tipoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsumoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_insumos.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_pedido', to='gestion_insumos.pedido_proveedor')),
            ],
        ),
    ]
