# Generated by Django 5.1.2 on 2024-11-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_insumos', '0002_remove_insumo_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('kilogramos', 'Kilogramos'), ('litros', 'Litros'), ('unidad', 'Unidad'), ('gramos', 'Gramos')], default='Kilogramos', max_length=20),
        ),
    ]
