# Generated by Django 5.1.2 on 2024-11-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_insumos', '0003_insumo_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_insumos.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_pedido', to='gestion_insumos.pedido_proveedor')),
            ],
        ),
    ]
