# Generated by Django 5.1.2 on 2024-11-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('unidad', 'Unidad')], default='unidad', max_length=10)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('punto_reposicion', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('panificación', 'Panificación'), ('pastelería', 'Pastalería')], max_length=50)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
