# Generated by Django 5.1.2 on 2024-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('panificación', 'Panificación'), ('pastelería', 'Pastalería')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reposicion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
